SET CLIENT_ENCODING TO 'UTF8';

CREATE TABLE USER_BV (
	ID SERIAL NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	SURNAME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	IS_VALID BOOLEAN NOT NULL,
	PRIMARY KEY (ID)
);